import { FileItem } from '@/applications/file-manager/types';

export const mockFiles: FileItem[] = [
  {
    id: '1',
    name: 'Marketing Projects',
    type: 'folder',
    isShared: false,
    access: { type: 'only_you' },
    isStarred: false,
    modified: null,
    size: 0,
    extension: '',
    itemsCount: 12,
  },
  {
    id: '2',
    name: 'Personal Photos',
    type: 'folder',
    isShared: false,
    access: { type: 'only_you' },
    isStarred: true,
    modified: null,
    size: 0,
    extension: '',
    itemsCount: 153,
  },
  {
    id: '3',
    name: 'Archived Invoices',
    type: 'folder',
    isShared: false,
    access: { type: 'only_you' },
    isStarred: false,
    modified: null,
    size: 0,
    extension: '',
    itemsCount: 5,
  },
  {
    id: '4',
    name: 'Q4 Team Sync',
    type: 'shared_folder',
    isShared: true,
    access: { type: 'members', count: 8 },
    isStarred: true,
    modified: null,
    size: 0,
    extension: '',
    itemsCount: 21,
  },
  {
    id: '5',
    name: 'Design Resources',
    type: 'shared_folder',
    isShared: true,
    access: { type: 'members', count: 12 },
    isStarred: false,
    modified: null,
    size: 0,
    extension: '',
    itemsCount: 8,
  },
  {
    id: '6',
    name: 'company-logo-final.svg',
    type: 'image',
    isShared: false,
    access: { type: 'only_you' },
    isStarred: false,
    modified: new Date('2024-05-20T11:30:00'),
    thumbnailUrl: 'https://picsum.photos/id/1074/200/200',
    size: 15 * 1024,
    extension: 'svg',
    itemsCount: null,
  },
  {
    id: '7',
    name: 'beach-sunset.jpg',
    type: 'image',
    isShared: false,
    access: { type: 'only_you' },
    isStarred: true,
    modified: new Date('2023-08-15T18:45:10'),
    thumbnailUrl: 'https://picsum.photos/id/1015/200/200',
    size: 4.2 * 1024 * 1024,
    extension: 'jpg',
    itemsCount: null,
  },
  {
    id: '8',
    name: 'wireframe-screenshot.png',
    type: 'image',
    isShared: false,
    access: { type: 'only_you' },
    isStarred: false,
    modified: new Date('2024-07-01T09:12:54'),
    thumbnailUrl: 'https://picsum.photos/id/1/200/200',
    size: 312 * 1024,
    extension: 'png',
    itemsCount: null,
  },
  {
    id: '9',
    name: 'Service_Agreement.pdf',
    type: 'pdf',
    isShared: true,
    access: { type: 'members', count: 3 },
    isStarred: true,
    modified: new Date('2024-06-25T14:00:21'),
    size: 450 * 1024,
    extension: 'pdf',
    itemsCount: null,
  },
  {
    id: '10',
    name: 'Annual_Report_2023.pdf',
    type: 'pdf',
    isShared: false,
    access: { type: 'only_you' },
    isStarred: false,
    modified: new Date('2024-02-10T16:22:00'),
    size: 12 * 1024 * 1024,
    extension: 'pdf',
    itemsCount: null,
  },
  {
    id: '11',
    name: 'Onboarding_Manual.pdf',
    type: 'pdf',
    isShared: false,
    access: { type: 'only_you' },
    isStarred: false,
    modified: new Date('2022-11-30T10:05:00'),
    size: 850 * 1024,
    extension: 'pdf',
    itemsCount: null,
  },
  {
    id: '12',
    name: 'website_backup_july.zip',
    type: 'zip',
    isShared: false,
    access: { type: 'only_you' },
    isStarred: false,
    modified: new Date('2024-07-10T03:30:00'),
    size: 256 * 1024 * 1024,
    extension: 'zip',
    itemsCount: null,
  },
  {
    id: '13',
    name: 'project_source_code.zip',
    type: 'zip',
    isShared: false,
    access: { type: 'only_you' },
    isStarred: false,
    modified: new Date('2024-01-15T22:50:14'),
    size: 32 * 1024 * 1024,
    extension: 'zip',
    itemsCount: null,
  },
  {
    id: '14',
    name: 'Figma Design Mockups.url',
    type: 'link',
    isShared: true,
    access: { type: 'members', count: 5 },
    isStarred: true,
    modified: new Date('2024-06-18T13:00:00'),
    size: 1 * 1024,
    extension: 'url',
    itemsCount: null,
  },
  {
    id: '15',
    name: 'Project Plan - Google Sheet.url',
    type: 'link',
    isShared: false,
    access: { type: 'only_you' },
    isStarred: false,
    modified: new Date('2024-04-05T17:18:29'),
    size: 1 * 1024,
    extension: 'url',
    itemsCount: null,
  },
  {
    id: '16',
    name: 'Meeting Notes 2024-07-09.rtf',
    type: 'rtf',
    isShared: false,
    access: { type: 'only_you' },
    isStarred: false,
    modified: new Date('2024-07-09T11:45:00'),
    size: 25 * 1024,
    extension: 'rtf',
    itemsCount: null,
  },
  {
    id: '17',
    name: 'Article Draft.rtf',
    type: 'rtf',
    isShared: false,
    access: { type: 'only_you' },
    isStarred: false,
    modified: new Date('2024-05-12T20:11:34'),
    size: 128 * 1024,
    extension: 'rtf',
    itemsCount: null,
  },
  {
    id: '18',
    name: 'sitemap_export.xml',
    type: 'document',
    isShared: false,
    access: { type: 'only_you' },
    isStarred: false,
    modified: new Date('2023-12-01T19:00:00'),
    size: 2.1 * 1024 * 1024,
    extension: 'xml',
    itemsCount: null,
  },
];
