export type Email = {
  id: string;
  from: string;
  status: 'starred' | 'default';
  subject: string;
  text: string;
  date: string;
  isRead: boolean;
};

export const emails: Email[] = [
  {
    id: '1',
    from: "Liam O'Connor",
    status: 'default',
    subject: 'New Task Assigned: Authentication Module for Project Phoenix',
    text: "Hi Eleanor, I've assigned a new high-priority task to you in Jira (IS-182): 'Develop and implement the new authentication module for the Phoenix client app'. The deadline is three weeks from today. Please review the attached technical specifications.",
    date: '10:32 AM',
    isRead: false,
  },
  {
    id: '2',
    from: 'Dr. Aris Thorne',
    status: 'default',
    subject: 'Q4 Product Roadmap Presentation',
    text: 'Hi Alex, a reminder that the Q4 product roadmap presentation for the exec team is this Friday. Please upload the final draft to the shared drive by EOD Thursday. Looking forward to seeing the market research insights.',
    date: '9:15 AM',
    isRead: false,
  },
  {
    id: '3',
    from: 'Chloe Bennet',
    status: 'default',
    subject: "RE: Budget Approval for 'VitaFresh' Juice Campaign",
    text: "Hi Sophia, great news! The finance department has approved the budget for the 'VitaFresh' autumn marketing campaign. You can now move forward with briefing the creative agency. Keep me in the loop.",
    date: 'Yesterday',
    isRead: true,
  },
  {
    id: '4',
    from: 'JIRA (AeroGlide Dynamics)',
    status: 'default',
    subject: '[JIRA] (AGD-301) Task Updated: Wind Tunnel Test Results',
    text: "David, the latest CFD simulation results for the 'Condor-5' wing optimization have been attached to task AGD-301. Please review the data and prepare the prototype for wind tunnel testing next week.",
    date: 'Yesterday',
    isRead: true,
  },
  {
    id: '5',
    from: 'Isabella Rossi',
    status: 'default',
    subject: "Feedback on 'Moon Wanderer' Concept Art",
    text: "Hi Maria, I've just reviewed the initial character sketches for 'Moon Wanderer'. I love the direction! I've left some detailed comments on the shared Figma file. Let's discuss them during our 3 PM sync today.",
    date: 'Yesterday',
    isRead: false,
  },
  {
    id: '6',
    from: 'Samuel Jones',
    status: 'starred',
    subject: "Kick-off Meeting: 'Global Logistics' Pilot Project",
    text: "Ian, I've scheduled the official kick-off meeting with the team at 'Global Logistics' for next Tuesday at 10 AM. The agenda will cover technical requirements, installation timeline, and staff training. Please come prepared.",
    date: 'Jul 22',
    isRead: true,
  },
  {
    id: '7',
    from: 'Hannah Price (HR)',
    status: 'default',
    subject: 'Reminder: Annual Performance Reviews',
    text: 'Dear all, this is a friendly reminder that the deadline for completing your self-assessment for the annual performance review is this Friday, July 28th. Please access the form via the HR portal.',
    date: 'Jul 22',
    isRead: true,
  },
  {
    id: '8',
    from: 'Alex Chen',
    status: 'default',
    subject: 'Data request for churn prediction model',
    text: 'Hi Kevin, following up on our conversation, could you please pull the user activity data from the last 12 months? We need it to start building the new churn prediction model. Thanks!',
    date: 'Jul 21',
    isRead: true,
  },
  {
    id: '9',
    from: 'GitHub',
    status: 'default',
    subject: '[innovatech/phoenix] Pull request #118 needs your review',
    text: "@eleanorvance, Liam O'Connor requested your review on pull request #118: 'feat: Add base structure for OAuth2 module'. You can view, comment on, or merge this pull request online.",
    date: 'Jul 21',
    isRead: false,
  },
  {
    id: '10',
    from: 'Culture Committee',
    status: 'default',
    subject: "You're Invited! Summer BBQ Party!",
    text: 'Get ready to grill and chill! The annual GreenLeaf Organics Summer BBQ is happening on Friday, August 8th. Join us for great food and fun games. Please RSVP by next Monday so we can get a headcount.',
    date: 'Jul 21',
    isRead: true,
  },
  {
    id: '11',
    from: 'CarbonFibre Co. Sales',
    status: 'default',
    subject: 'Your Quote for Carbon Fiber Sheeting (AGD-Q3-487)',
    text: 'Dear David Miles, thank you for your inquiry. Please find attached the quote for your requested order of T700 carbon fiber sheets. The lead time is currently 4-6 weeks.',
    date: 'Jul 20',
    isRead: true,
  },
  {
    id: '12',
    from: 'Asana',
    status: 'default',
    subject: 'Isabella Rossi assigned you "Finalize character color palettes"',
    text: "Hi Maria, Isabella Rossi has assigned you a new task in the 'Moon Wanderer - Pre-production' project. The due date is next Wednesday.",
    date: 'Jul 20',
    isRead: true,
  },
  {
    id: '13',
    from: 'Ian Stone',
    status: 'default',
    subject: 'Following up on our meeting',
    text: "Dear Mr. Harris, it was a pleasure speaking with you today. As discussed, I've attached the preliminary project plan for the pilot implementation of our 'SortBot-3000' system. We are excited to move forward.",
    date: 'Jul 19',
    isRead: true,
  },
  {
    id: '14',
    from: 'Dr. Aris Thorne',
    status: 'default',
    subject: 'Tech Talk Invitation: "The Ethics of AI in Predictive Analytics"',
    text: "Team, I'd like to invite you all to a special tech talk next Thursday by guest speaker Dr. Evelyn Reed. She will be discussing the ethical considerations and challenges in AI. Don't miss this insightful session.",
    date: 'Jul 19',
    isRead: true,
  },
  {
    id: '15',
    from: 'IT Security',
    status: 'default',
    subject: 'Security Alert: Phishing Awareness Reminder',
    text: 'This is a company-wide security reminder. We have noticed an increase in phishing attempts. Please be vigilant and do not click on suspicious links or download attachments from unknown senders.',
    date: 'Jul 18',
    isRead: true,
  },
  {
    id: '16',
    from: 'Sarah Jenkins',
    status: 'starred',
    subject: 'Love the new juices!',
    text: "I just wanted to say that I tried your new 'VitaFresh' green juice and it's absolutely delicious! Best organic juice I've had in a long time. Keep up the great work!",
    date: 'Jul 18',
    isRead: true,
  },
  {
    id: '17',
    from: 'Toon Boom Animation',
    status: 'default',
    subject: 'Your Storyboard Pro subscription has been updated',
    text: 'Dear Starlight Studios, your team subscription for Toon Boom Storyboard Pro has been successfully renewed and updated to the latest version. Enjoy the new features!',
    date: 'Jul 17',
    isRead: true,
  },
  {
    id: '18',
    from: 'Nexus Robotics Monitoring',
    status: 'default',
    subject: 'System Status Update: All Systems Operational',
    text: "This is an automated message. All robotic systems at client 'Global Logistics' are currently operational. No anomalies detected in the last 24 hours. System efficiency is at 99.8%.",
    date: 'Jul 17',
    isRead: true,
  },
  {
    id: '19',
    from: 'Slack',
    status: 'default',
    subject: "You have a new direct message from Liam O'Connor",
    text: 'Liam O\'Connor: "Hey Eleanor, do you have a minute to sync on the auth module? I have a couple of questions about the JWT implementation."',
    date: 'Jul 17',
    isRead: false,
  },
  {
    id: '20',
    from: 'Google Calendar',
    status: 'default',
    subject:
      'Invitation: Project Phoenix: Sprint Retrospective @ Wed Jul 19, 2025 4pm - 5pm',
    text: "Liam O'Connor is inviting you to a meeting. Please RSVP.",
    date: 'Jul 17',
    isRead: true,
  },
  {
    id: '21',
    from: 'QA Team',
    status: 'default',
    subject: 'CRITICAL BUG FOUND: [PHX-211] User data leak on profile update',
    text: 'A critical security vulnerability has been identified in the latest build on the staging server. All developers on Project Phoenix, please review the bug report immediately.',
    date: 'Jul 16',
    isRead: true,
  },
  {
    id: '22',
    from: 'Oliver Chen (Starlight Studios)',
    status: 'default',
    subject:
      "Review needed: First pass animation for Scene 24 of 'Moon Wanderer'",
    text: "Hi Maria, the team has finished the first pass on Scene 24. It's ready for your review in the project drive. Let us know your thoughts.",
    date: 'Jul 16',
    isRead: false,
  },
  {
    id: '23',
    from: 'FreshMart Procurement',
    status: 'default',
    subject: 'New Partnership Opportunity',
    text: "Dear GreenLeaf Organics team, we are impressed with your 'VitaFresh' line and would like to discuss a potential partnership to feature it in our stores nationwide.",
    date: 'Jul 15',
    isRead: true,
  },
  {
    id: '24',
    from: 'AWS',
    status: 'default',
    subject: 'Your AWS bill for June 2025 is now available',
    text: 'Your estimated bill for Amazon Web Services (AWS) for the month of June has been calculated. Please review your billing console for detailed information.',
    date: 'Jul 15',
    isRead: true,
  },
  {
    id: '25',
    from: 'David Miles',
    status: 'starred',
    subject: 'URGENT: Issue with Condor-5 prototype',
    text: 'Team, during stress testing this morning, we observed a hairline fracture in the main chassis of the Condor-5 prototype. All further tests are suspended. Engineering leads to meet in 30 mins.',
    date: 'Jul 14',
    isRead: true,
  },
  {
    id: '26',
    from: 'Legal Team (Nexus Robotics)',
    status: 'default',
    subject: 'Action Required: Sign new NDA for Project Cygnus',
    text: 'To all personnel assigned to Project Cygnus, a new Non-Disclosure Agreement is required. Please sign the document via DocuSign by EOD tomorrow.',
    date: 'Jul 14',
    isRead: true,
  },
  {
    id: '27',
    from: 'Zendesk',
    status: 'default',
    subject: '[Ticket #88241] "My robot is moving in circles"',
    text: 'A new high-priority support ticket has been assigned to your team. Client: Global Logistics. Issue: One SortBot-3000 unit is malfunctioning on the main sorting line.',
    date: 'Jul 14',
    isRead: false,
  },
  {
    id: '28',
    from: 'Kevin Zhang',
    status: 'default',
    subject: 'Re: Data request for churn prediction model',
    text: 'Hi Alex, the data pull is complete. The dataset is now available in the /data/exports/ folder on the shared server. Let me know if you need anything else.',
    date: 'Jul 13',
    isRead: true,
  },
  {
    id: '29',
    from: 'Sophia Martinez',
    status: 'default',
    subject: 'Team Lunch!',
    text: "Hey team, let's celebrate the successful launch of the VitaFresh campaign! I'm booking a table at The Garden Eatery for this Friday at 1 PM. Who's in?",
    date: 'Jul 13',
    isRead: true,
  },
  {
    id: '30',
    from: 'AeroGlide Dynamics Travel Desk',
    status: 'default',
    subject: 'Your Flight Itinerary to Munich, Germany',
    text: 'Dear David Miles, your flight and hotel for your site visit to our carbon fiber supplier have been confirmed. Please find the details attached.',
    date: 'Jul 12',
    isRead: true,
  },
  {
    id: '31',
    from: 'Trello',
    status: 'default',
    subject: 'Chloe Bennet moved "Design social media banners" to "In Review"',
    text: 'Card "Design social media banners" in list "Doing" on board "VitaFresh Campaign" was moved to "In Review" by Chloe Bennet.',
    date: 'Jul 12',
    isRead: true,
  },
  {
    id: '32',
    from: 'Jenkins',
    status: 'default',
    subject: 'Build failed for innovatech/phoenix - branch: main',
    text: 'Build #482 for the main branch of innovatech/phoenix has failed. Check the console output for details.',
    date: 'Jul 11',
    isRead: true,
  },
  {
    id: '33',
    from: 'Maria Vega',
    status: 'default',
    subject: "Re: Feedback on 'Moon Wanderer' Concept Art",
    text: "Hi Isabella, thanks for the feedback! I've updated the character designs based on your notes. They are ready for another look.",
    date: 'Jul 11',
    isRead: true,
  },
  {
    id: '34',
    from: 'Dr. Aris Thorne',
    status: 'default',
    subject: 'Interesting article on market sentiment analysis',
    text: 'Team, I came across this paper on using transformer models for financial market sentiment analysis. A very relevant read for our current project. Link inside.',
    date: 'Jul 10',
    isRead: true,
  },
  {
    id: '35',
    from: 'Global Logistics IT',
    status: 'default',
    subject: 'Scheduled Maintenance for Warehouse API',
    text: 'Dear Nexus Robotics, this is to inform you that we will be performing scheduled maintenance on our Warehouse Management API this Saturday from 2 AM to 4 AM.',
    date: 'Jul 10',
    isRead: true,
  },
  {
    id: '36',
    from: 'Eleanor Vance',
    status: 'default',
    subject: 'Question about the database schema',
    text: "Hi Liam, I'm working on the auth module and noticed a potential issue with the `users` table schema. Do you have a moment to discuss?",
    date: 'Jul 9',
    isRead: true,
  },
  {
    id: '37',
    from: 'Adobe',
    status: 'default',
    subject: 'Your Creative Cloud membership has been renewed',
    text: 'Thank you, Starlight Studios. Your annual membership for Creative Cloud for teams has been successfully renewed. Your invoice is available for download.',
    date: 'Jul 9',
    isRead: true,
  },
  {
    id: '38',
    from: 'HR Department',
    status: 'default',
    subject: 'Welcome our new hires!',
    text: 'Please join us in giving a warm welcome to our two new software engineers, Ben Carter and Olivia White, who are joining the Innovatech team today!',
    date: 'Jul 8',
    isRead: true,
  },
  {
    id: '39',
    from: 'Sophia Martinez',
    status: 'starred',
    subject: 'Weekly Social Media Report',
    text: 'Team, please see attached the performance report for our social media channels. The VitaFresh campaign has resulted in a 35% increase in engagement!',
    date: 'Jul 8',
    isRead: true,
  },
  {
    id: '40',
    from: 'AutoCAD',
    status: 'default',
    subject: 'Your license is expiring soon',
    text: 'Dear David Miles, your AutoCAD license is set to expire in 15 days. Please contact your administrator to ensure uninterrupted access.',
    date: 'Jul 7',
    isRead: true,
  },
  {
    id: '41',
    from: 'Ian Stone',
    status: 'default',
    subject: 'Firmware Update v2.5.1 for SortBot-3000',
    text: 'Heads up team, we are planning to roll out firmware update v2.5.1 to all client fleets next Monday. This update includes performance improvements and bug fixes.',
    date: 'Jul 7',
    isRead: false,
  },
  {
    id: '42',
    from: 'Alex Chen',
    status: 'default',
    subject: 'Initial results from churn model',
    text: 'Hi Dr. Thorne, I have the initial results from the churn prediction model. The accuracy is promising at 87%. The full report is attached.',
    date: 'Jul 6',
    isRead: true,
  },
  {
    id: '43',
    from: 'Render Farm Admin',
    status: 'default',
    subject: 'Job complete: MW_Scene23_Final_Render.mb',
    text: 'Your render job for `MW_Scene23_Final_Render.mb` has completed successfully. Total render time: 48 hours, 15 minutes.',
    date: 'Jul 6',
    isRead: true,
  },
  {
    id: '44',
    from: "Liam O'Connor",
    status: 'default',
    subject: 'Code Freeze for v1.2 Release',
    text: 'Project Phoenix team: A reminder that the code freeze for the v1.2 release is this Friday at 5 PM. Please merge all final PRs before then.',
    date: 'Jul 5',
    isRead: true,
  },
  {
    id: '45',
    from: 'Customer Support (GreenLeaf)',
    status: 'default',
    subject: 'FW: Question about nut allergies',
    text: 'Hi Sophia, can you confirm if the VitaFresh Tropical blend is produced in a nut-free facility? A customer has a severe allergy concern.',
    date: 'Jul 5',
    isRead: false,
  },
  {
    id: '46',
    from: 'Dribbble',
    status: 'default',
    subject: 'Starlight Studios, you have 1 new follower',
    text: 'Your profile has a new follower! People are noticing your work.',
    date: 'Jul 4',
    isRead: true,
  },
  {
    id: '47',
    from: 'Facilities Management',
    status: 'default',
    subject: 'Fire Drill this Thursday',
    text: 'This is to inform all employees that a mandatory fire drill will be conducted this Thursday at 11 AM. Please familiarize yourself with the evacuation routes.',
    date: 'Jul 4',
    isRead: true,
  },
  {
    id: '48',
    from: 'David Miles',
    status: 'default',
    subject: 'Updated CAD files for Condor-5 chassis',
    text: 'Team, I have uploaded the revised CAD designs for the Condor-5 chassis to the shared drive. Please review the changes.',
    date: 'Jul 3',
    isRead: true,
  },
  {
    id: '49',
    from: 'Google Alerts',
    status: 'default',
    subject: 'Google Alert - "QuantumLeap Analytics"',
    text: 'TechCrunch: "QuantumLeap Analytics raises $20M in Series A funding to revolutionize financial forecasting..."',
    date: 'Jul 3',
    isRead: true,
  },
  {
    id: '50',
    from: 'Samuel Jones',
    status: 'default',
    subject: 'Weekly report from Global Logistics pilot',
    text: 'Hi Ian, please find the weekly performance and uptime report from the Global Logistics pilot attached. Efficiency is up by 12% since go-live.',
    date: 'Jul 2',
    isRead: true,
  },
  {
    id: '51',
    from: 'Eleanor Vance',
    status: 'default',
    subject: 'Vacation Request: August 14-21',
    text: 'Hi Liam, I am formally requesting vacation time from August 14th to August 21st. I will ensure all my critical tasks are handed over before I leave.',
    date: 'Jul 2',
    isRead: true,
  },
  {
    id: '52',
    from: 'Casting Director',
    status: 'default',
    subject: "Voice actor auditions for 'Moon Wanderer'",
    text: "Hi Maria, here are the first batch of audio auditions for the lead role. Let me know which ones you'd like to call back.",
    date: 'Jul 1',
    isRead: false,
  },
  {
    id: '53',
    from: 'GitHub',
    status: 'default',
    subject: '[nex-robotics/firmware] Pull request #24 has been merged',
    text: "Ian Stone merged pull request #24: 'fix: Improve obstacle detection algorithm'.",
    date: 'Jun 30',
    isRead: true,
  },
  {
    id: '54',
    from: 'Chloe Bennet',
    status: 'default',
    subject: 'Printing quotes for new packaging',
    text: "Hi Sophia, I've received quotes from three different printers for the new VitaFresh bottle labels. The breakdown is attached for your review.",
    date: 'Jun 30',
    isRead: true,
  },
  {
    id: '55',
    from: 'IT Help Desk',
    status: 'default',
    subject: 'Your ticket #5821 has been resolved',
    text: 'Your issue "Cannot connect to VPN" has been resolved. If you are still experiencing problems, please reopen the ticket.',
    date: 'Jun 29',
    isRead: true,
  },
  {
    id: '56',
    from: 'Bloomberg',
    status: 'default',
    subject: 'Your Bloomberg Terminal subscription renewal',
    text: 'Dear Dr. Thorne, this is a notification that your subscription to the Bloomberg Terminal is due for renewal next month.',
    date: 'Jun 29',
    isRead: true,
  },
  {
    id: '57',
    from: 'LogiTech Expo 2025',
    status: 'starred',
    subject: 'Your Speaker Application has been Accepted!',
    text: 'Dear Ian Stone, congratulations! Your proposal "The Future of Warehouse Automation" has been accepted for a breakout session at LogiTech Expo 2025.',
    date: 'Jun 28',
    isRead: true,
  },
  {
    id: '58',
    from: 'Figma',
    status: 'default',
    subject: 'Liam O\'Connor commented on "Phoenix - Login UI"',
    text: 'Comment: "Can we try a version with the Google SSO button more prominent?"',
    date: 'Jun 28',
    isRead: true,
  },
  {
    id: '59',
    from: 'UPS My Choice',
    status: 'default',
    subject:
      'Your package from Digi-Key Electronics is scheduled for delivery tomorrow',
    text: 'A package containing electronic components for AeroGlide Dynamics is on its way.',
    date: 'Jun 27',
    isRead: true,
  },
  {
    id: '60',
    from: 'HR Department',
    status: 'default',
    subject: 'Update to company WFH policy',
    text: "Dear all, please note that the company's work-from-home policy has been updated. Please review the new guidelines in the company handbook.",
    date: 'Jun 27',
    isRead: false,
  },
  {
    id: '61',
    from: 'Isabella Rossi',
    status: 'default',
    subject: "Press Release Draft for 'Moon Wanderer'",
    text: 'Hi Maria, here is the first draft of the press release announcing our new film. Please provide your feedback.',
    date: 'Jun 26',
    isRead: true,
  },
  {
    id: '62',
    from: 'SurveyMonkey',
    status: 'default',
    subject: 'Results are in for "Employee Satisfaction Survey"',
    text: 'View the summary and individual responses for the Q2 Employee Satisfaction Survey.',
    date: 'Jun 26',
    isRead: true,
  },
  {
    id: '63',
    from: 'Miro',
    status: 'default',
    subject: 'Alex Chen invited you to view the board "Q4 Roadmap Brainstorm"',
    text: 'Join the board to add your ideas for the upcoming quarter.',
    date: 'Jun 25',
    isRead: true,
  },
  {
    id: '64',
    from: 'Supplier - Omni Plastics',
    status: 'default',
    subject: 'Re: PO# 78552 - ETA for Robot Chassis',
    text: 'Hi Ian, we can confirm that your order of 500 robot chassis units will be ready for shipment by July 15th.',
    date: 'Jun 24',
    isRead: true,
  },
  {
    id: '65',
    from: 'The Organic Times',
    status: 'default',
    subject: 'Request for interview with GreenLeaf Organics CEO',
    text: 'We are writing a feature on sustainable farming and would love to interview your CEO. Are they available for a brief chat next week?',
    date: 'Jun 24',
    isRead: false,
  },
  {
    id: '66',
    from: 'Eleanor Vance',
    status: 'default',
    subject: 'Documentation for the new Auth API',
    text: 'Hi team, I have completed the preliminary documentation for the new authentication API. You can find it on our Confluence space. Feedback is welcome.',
    date: 'Jun 23',
    isRead: true,
  },
  {
    id: '67',
    from: 'Glassdoor',
    status: 'default',
    subject: 'A new review has been posted for Innovatech Solutions',
    text: 'A former employee has left a review. See what they had to say about their experience.',
    date: 'Jun 23',
    isRead: true,
  },
  {
    id: '68',
    from: 'David Miles',
    status: 'starred',
    subject: 'SUCCESS! Condor-5 prototype flight time increased by 18%!',
    text: "Team, the results from today's field test are in. The new chassis design is a massive success, exceeding our initial target. Fantastic work, everyone!",
    date: 'Jun 22',
    isRead: true,
  },
];
